# Generated by Django 4.1.2 on 2024-07-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department", old_name="department_name", new_name="title",
        ),
    ]
