# Generated by Django 4.1.2 on 2024-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=10, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(max_length=10, unique=True, verbose_name="用户名"),
        ),
    ]
