# Generated by Django 4.1.2 on 2024-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0002_alter_admin_password_alter_admin_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=50, verbose_name="密码"),
        ),
    ]
