# Generated by Django 4.1.2 on 2024-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee", name="gender", field=models.IntegerField(),
        ),
    ]
