# Generated by Django 4.1.2 on 2024-08-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_delete_employee"),
        ("user", "0002_alter_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.IntegerField(verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=20, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=20, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.IntegerField(default=0, verbose_name="余额"),
        ),
    ]
